blueprint:
  name: Afzuiginstallatie Temperatuurregeling v1.5
  description: >
    Regelt de afzuiginstallatie afhankelijk van temperatuurverschillen.
    Werkt met een dimbare lichtentiteit (bijv. fan via Zigbee light).
    Alleen actief als buitenlucht koeler is dan binnenlucht én temperatuur boven richtpunt ligt.

  domain: automation

  input:
    binnen_temp_sensor:
      name: "Primaire Binnentemperatuursensor"
      description: "Sensor voor de temperatuur in de ruimte die wordt afgevoerd."
      selector:
        entity:
          domain: sensor
          device_class: temperature

    controle_binnen_sensor:
      name: "Vergelijkingssensor Binnen (optioneel)"
      description: >
        Sensor voor andere binnenruimte (bijv. woonkamer), zodat er geen warme buitenlucht
        wordt aangezogen als het buiten warmer is dan binnen.
      default: ""
      selector:
        entity:
          domain: sensor
          device_class: temperature

    buiten_temp_sensor:
      name: "Buitentemperatuursensor"
      description: "Sensor of weersensor met buitentemperatuur in een attribuut of state."
      selector:
        entity:
          domain: sensor

    buiten_temp_attribute:
      name: "Optioneel: Attribuut voor buitentemperatuur"
      description: "Laat leeg als de sensor de temperatuur direct als state bevat."
      default: ""
      selector:
        text:

    afzuiginstallatie_light:
      name: "Afzuiginstallatie Licht (dimbaar)"
      description: "Lichtentiteit die de afzuiging aanstuurt via dimniveau."
      selector:
        entity:
          domain: light

    richttemperatuur:
      name: "Richttemperatuur binnen"
      default: 21.0
      selector:
        number:
          min: 10
          max: 30
          step: 0.5
          unit_of_measurement: "°C"

    hysteresis:
      name: "Hysteresis"
      default: 0.5
      selector:
        number:
          min: 0.1
          max: 5.0
          step: 0.1
          unit_of_measurement: "°C"

triggers:
  - platform: state
    entity_id: !input binnen_temp_sensor
    for: "00:01:00"
  - platform: state
    entity_id: !input buiten_temp_sensor
    for: "00:01:00"

conditions: []

actions:
  - variables:
      binnen_temp_sensor_id: !input binnen_temp_sensor
      buiten_temp_sensor_id: !input buiten_temp_sensor
      controle_binnen_sensor_id: !input controle_binnen_sensor
      buiten_temp_attr: !input buiten_temp_attribute
      richt: !input richttemperatuur
      marge: !input hysteresis

      binnen: >
        {{ states(binnen_temp_sensor_id) | float(0) }}

      buiten: >
        {% if buiten_temp_attr %}
          {{ state_attr(buiten_temp_sensor_id, buiten_temp_attr) | float(0) }}
        {% else %}
          {{ states(buiten_temp_sensor_id) | float(0) }}
        {% endif %}

      controlebinnen: >
        {% if controle_binnen_sensor_id %}
          {{ states(controle_binnen_sensor_id) | float(21.0) }}
        {% else %}
          {{ 21.0 }}
        {% endif %}

      verschil: "{{ binnen - buiten }}"

  - service: system_log.write
    data:
      level: info
      message: >
        Afzuigcontrole uitgevoerd. Binnen: {{ binnen }}°C,
        Buiten: {{ buiten }}°C,
        Verschil: {{ verschil }}°C,
        Richt: {{ richt }}°C,
        Controlebinnen: {{ controlebinnen }}°C

  - choose:
      - conditions:
          - condition: template
            value_template: >
              {{ verschil > 1.5 and buiten < controlebinnen and binnen > richt + marge }}
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input afzuiginstallatie_light
            data:
              brightness_pct: 100

      - conditions:
          - condition: template
            value_template: >
              {{ verschil > 0.8 and verschil <= 1.5 and buiten < controlebinnen and binnen > richt + marge }}
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input afzuiginstallatie_light
            data:
              brightness_pct: 66

      - conditions:
          - condition: template
            value_template: >
              {{ verschil > 0 and verschil <= 0.8 and buiten < controlebinnen and binnen > richt + marge }}
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input afzuiginstallatie_light
            data:
              brightness_pct: 33

      - conditions:
          - condition: template
            value_template: >
              {{ verschil <= 0 or buiten >= controlebinnen or binnen <= richt }}
        sequence:
          - service: light.turn_off
            target:
              entity_id: !input afzuiginstallatie_light

mode: single
