blueprint:
  name: GMS Insecten Verdelging v4.30
  description: >
    Automatische bediening van insectenlampen op basis van weersomstandigheden en seizoensmodi.
    ✅ Ondersteuning voor zowel lampen (light) als slimme stekkers (switch), ook gecombineerd.
    ✅ Regenwaarde wordt via een helper-sensor ingelezen (None wordt afgevangen).
    ✅ Seizoenslogica stuurt cycli, pauzes en duur aan per stand.
    ✅ Geschikt voor gebruik zonder !include in blueprint acties.

  domain: automation
  input:
    lampen_switch:
      name: Insectenlampen (Switches)
      description: Selecteer de insectenlampen van het type 'switch'. Laat leeg indien niet van toepassing.
      default: {}
      selector:
        target:
          entity:
            domain: switch

    lampen_light:
      name: Insectenlampen (Lampen)
      description: Selecteer de insectenlampen van het type 'light'. Laat leeg indien niet van toepassing.
      default: {}
      selector:
        target:
          entity:
            domain: light

    weersensor:
      name: Weersensor
      description: Selecteer de weersensor (zoals weather.buienradar).
      selector:
        entity:
          domain: weather

    neerslag_helper:
      name: Neerslagwaarde Helper
      description: Een aparte template sensor die de neerslagwaarde uitleest en bij None fallbackt naar 0.0.
      selector:
        entity:
          domain: sensor

    min_temp:
      name: Minimale Temperatuur
      default: 13
      selector:
        number:
          min: 0
          max: 25
          unit_of_measurement: °C

    max_temp:
      name: Maximale Temperatuur
      default: 35
      selector:
        number:
          min: 25
          max: 40
          unit_of_measurement: °C

    min_humidity:
      name: Minimale Luchtvochtigheid
      default: 60
      selector:
        number:
          min: 50
          max: 70
          unit_of_measurement: '%'

    max_rain:
      name: Maximale Regenintensiteit
      default: 0.5
      selector:
        number:
          min: 0
          max: 2
          unit_of_measurement: 'mm/h'

    vacation_mode:
      name: Vakantiemodus
      selector:
        entity:
          domain: input_boolean

    seizoensmodus:
      name: Seizoensmodus
      selector:
        entity:
          domain: input_select

    insect_lamp_duration_summer:
      default: 15
      selector:
        number:
          min: 5
          max: 60
          unit_of_measurement: 'minuten'

    insect_lamp_cycles_summer:
      default: 4
      selector:
        number:
          min: 1
          max: 10
          unit_of_measurement: 'cycli'

    pause_between_cycles_summer:
      default: 30
      selector:
        number:
          min: 10
          max: 60
          unit_of_measurement: 'minuten'

    insect_lamp_duration_winter:
      default: 10
      selector:
        number:
          min: 5
          max: 60
          unit_of_measurement: 'minuten'

    insect_lamp_cycles_winter:
      default: 2
      selector:
        number:
          min: 1
          max: 5
          unit_of_measurement: 'cycli'

    pause_between_cycles_winter:
      default: 60
      selector:
        number:
          min: 30
          max: 120
          unit_of_measurement: 'minuten'

    insect_lamp_duration_herfst:
      default: 9
      selector:
        number:
          min: 5
          max: 60
          unit_of_measurement: 'minuten'

    insect_lamp_cycles_herfst:
      default: 2
      selector:
        number:
          min: 1
          max: 10
          unit_of_measurement: 'cycli'

    pause_between_cycles_herfst:
      default: 45
      selector:
        number:
          min: 10
          max: 90
          unit_of_measurement: 'minuten'

    insect_lamp_duration_lente:
      default: 12
      selector:
        number:
          min: 5
          max: 60
          unit_of_measurement: 'minuten'

    insect_lamp_cycles_lente:
      default: 3
      selector:
        number:
          min: 1
          max: 10
          unit_of_measurement: 'cycli'

    pause_between_cycles_lente:
      default: 45
      selector:
        number:
          min: 10
          max: 90
          unit_of_measurement: 'minuten'

trigger:
  - platform: time
    at: "00:00:00"
  - platform: time_pattern
    hours: "/2"
    minutes: 0

condition:
  - condition: numeric_state
    entity_id: !input weersensor
    attribute: temperature
    above: !input min_temp
    below: !input max_temp

  - condition: numeric_state
    entity_id: !input weersensor
    attribute: humidity
    above: !input min_humidity

  - condition: numeric_state
    entity_id: !input neerslag_helper
    below: !input max_rain

  - condition: state
    entity_id: !input vacation_mode
    state: 'off'

action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ states(!input seizoensmodus) == 'Zomerstand' }}"
        sequence:
          - service: homeassistant.turn_on
            target:
              entity_id: >
                {{ (lampen_switch.entity_id | default([])) + (lampen_light.entity_id | default([])) }}
          - delay:
              minutes: !input insect_lamp_duration_summer
          - service: homeassistant.turn_off
            target:
              entity_id: >
                {{ (lampen_switch.entity_id | default([])) + (lampen_light.entity_id | default([])) }}
          - repeat:
              count: !input insect_lamp_cycles_summer
              sequence:
                - delay:
                    minutes: !input pause_between_cycles_summer
                - service: homeassistant.turn_on
                  target:
                    entity_id: >
                      {{ (lampen_switch.entity_id | default([])) + (lampen_light.entity_id | default([])) }}
                - delay:
                    minutes: !input insect_lamp_duration_summer
                - service: homeassistant.turn_off
                  target:
                    entity_id: >
                      {{ (lampen_switch.entity_id | default([])) + (lampen_light.entity_id | default([])) }}

      - conditions:
          - condition: template
            value_template: "{{ states(!input seizoensmodus) == 'Winterstand' }}"
        sequence:
          - service: homeassistant.turn_on
            target:
              entity_id: >
                {{ (lampen_switch.entity_id | default([])) + (lampen_light.entity_id | default([])) }}
          - delay:
              minutes: !input insect_lamp_duration_winter
          - service: homeassistant.turn_off
            target:
              entity_id: >
                {{ (lampen_switch.entity_id | default([])) + (lampen_light.entity_id | default([])) }}
          - repeat:
              count: !input insect_lamp_cycles_winter
              sequence:
                - delay:
                    minutes: !input pause_between_cycles_winter
                - service: homeassistant.turn_on
                  target:
                    entity_id: >
                      {{ (lampen_switch.entity_id | default([])) + (lampen_light.entity_id | default([])) }}
                - delay:
                    minutes: !input insect_lamp_duration_winter
                - service: homeassistant.turn_off
                  target:
                    entity_id: >
                      {{ (lampen_switch.entity_id | default([])) + (lampen_light.entity_id | default([])) }}

      - conditions:
          - condition: template
            value_template: "{{ states(!input seizoensmodus) == 'Herfststand' }}"
        sequence:
          - service: homeassistant.turn_on
            target:
              entity_id: >
                {{ (lampen_switch.entity_id | default([])) + (lampen_light.entity_id | default([])) }}
          - delay:
              minutes: !input insect_lamp_duration_herfst
          - service: homeassistant.turn_off
            target:
              entity_id: >
                {{ (lampen_switch.entity_id | default([])) + (lampen_light.entity_id | default([])) }}
          - repeat:
              count: !input insect_lamp_cycles_herfst
              sequence:
                - delay:
                    minutes: !input pause_between_cycles_herfst
                - service: homeassistant.turn_on
                  target:
                    entity_id: >
                      {{ (lampen_switch.entity_id | default([])) + (lampen_light.entity_id | default([])) }}
                - delay:
                    minutes: !input insect_lamp_duration_herfst
                - service: homeassistant.turn_off
                  target:
                    entity_id: >
                      {{ (lampen_switch.entity_id | default([])) + (lampen_light.entity_id | default([])) }}

      - conditions:
          - condition: template
            value_template: "{{ states(!input seizoensmodus) == 'Lentestand' }}"
        sequence:
          - service: homeassistant.turn_on
            target:
              entity_id: >
                {{ (lampen_switch.entity_id | default([])) + (lampen_light.entity_id | default([])) }}
          - delay:
              minutes: !input insect_lamp_duration_lente
          - service: homeassistant.turn_off
            target:
              entity_id: >
                {{ (lampen_switch.entity_id | default([])) + (lampen_light.entity_id | default([])) }}
          - repeat:
              count: !input insect_lamp_cycles_lente
              sequence:
                - delay:
                    minutes: !input pause_between_cycles_lente
                - service: homeassistant.turn_on
                  target:
                    entity_id: >
                      {{ (lampen_switch.entity_id | default([])) + (lampen_light.entity_id | default([])) }}
                - delay:
                    minutes: !input insect_lamp_duration_lente
                - service: homeassistant.turn_off
                  target:
                    entity_id: >
                      {{ (lampen_switch.entity_id | default([])) + (lampen_light.entity_id | default([])) }}

    default:
      - service: homeassistant.turn_off
        target:
          entity_id: >
            {{ (lampen_switch.entity_id | default([])) + (lampen_light.entity_id | default([])) }}

mode: restart
