blueprint:
  name: GMS Insecten Verdelging v4.32lights
  description: >
    Automatische bediening van insectenlampen op basis van seizoensmodi en weersomstandigheden.
    Toegevoegd: handmatige override via afstandsbediening (device trigger).

  domain: automation
  input:
    insectenlampen:
      name: Insectenlampen
      selector:
        target:
          entity:
            domain: light

    weersensor:
      name: Weersensor
      selector:
        entity:
          domain: weather

    min_temp:
      name: Minimale Temperatuur
      default: 13
      selector:
        number:
          min: 0
          max: 25
          unit_of_measurement: "°C"

    max_temp:
      name: Maximale Temperatuur
      default: 35
      selector:
        number:
          min: 25
          max: 40
          unit_of_measurement: "°C"

    min_humidity:
      name: Minimale Luchtvochtigheid
      default: 60
      selector:
        number:
          min: 50
          max: 70
          unit_of_measurement: "%"

    max_rain:
      name: Maximale Regenintensiteit
      default: 0.5
      selector:
        number:
          min: 0
          max: 2
          unit_of_measurement: "mm/h"

    vacation_mode:
      name: Vakantieschakelaar
      selector:
        entity:
          domain: input_boolean

    seizoensmodus:
      name: Seizoensmodus
      selector:
        entity:
          domain: input_select

    insect_lamp_duration_summer:
      name: Zomer - Tijd aan (minuten)
      default: 15
      selector:
        number:
          min: 5
          max: 60
          unit_of_measurement: "minuten"

    insect_lamp_cycles_summer:
      name: Zomer - Aantal cycli
      default: 4
      selector:
        number:
          min: 1
          max: 10
          unit_of_measurement: "cycli"

    pause_between_cycles_summer:
      name: Zomer - Pauze (minuten)
      default: 30
      selector:
        number:
          min: 10
          max: 60
          unit_of_measurement: "minuten"

    insect_lamp_duration_winter:
      name: Winter - Tijd aan (minuten)
      default: 10
      selector:
        number:
          min: 5
          max: 60
          unit_of_measurement: "minuten"

    insect_lamp_cycles_winter:
      name: Winter - Aantal cycli
      default: 2
      selector:
        number:
          min: 1
          max: 5
          unit_of_measurement: "cycli"

    pause_between_cycles_winter:
      name: Winter - Pauze (minuten)
      default: 60
      selector:
        number:
          min: 30
          max: 120
          unit_of_measurement: "minuten"

    insect_lamp_duration_herfst:
      name: Herfst - Tijd aan (minuten)
      default: 9
      selector:
        number:
          min: 5
          max: 60
          unit_of_measurement: "minuten"

    insect_lamp_cycles_herfst:
      name: Herfst - Aantal cycli
      default: 2
      selector:
        number:
          min: 1
          max: 10
          unit_of_measurement: "cycli"

    pause_between_cycles_herfst:
      name: Herfst - Pauze (minuten)
      default: 45
      selector:
        number:
          min: 10
          max: 90
          unit_of_measurement: "minuten"

    insect_lamp_duration_lente:
      name: Lente - Tijd aan (minuten)
      default: 12
      selector:
        number:
          min: 5
          max: 60
          unit_of_measurement: "minuten"

    insect_lamp_cycles_lente:
      name: Lente - Aantal cycli
      default: 3
      selector:
        number:
          min: 1
          max: 10
          unit_of_measurement: "cycli"

    pause_between_cycles_lente:
      name: Lente - Pauze (minuten)
      default: 45
      selector:
        number:
          min: 10
          max: 90
          unit_of_measurement: "minuten"

    override_device:
      name: Afstandsbediening
      selector:
        device:
          filter:
            domain: hue

    override_button:
      name: Knopnummer (1-4)
      default: 1
      selector:
        select:
          options:
            - 1
            - 2
            - 3
            - 4

    override_duration:
      name: Tijd override (minuten)
      default: 10
      selector:
        number:
          min: 1
          max: 60
          unit_of_measurement: "minuten"

trigger:
  - platform: time
    at: "00:00:00"
  - platform: time_pattern
    hours: "/2"
    minutes: 0
  - platform: device
    device_id: !input override_device
    domain: hue
    type: initial_press
    subtype: !input override_button

condition:
  - condition: or
    conditions:
      - condition: and
        conditions:
          - condition: state
            entity_id: !input vacation_mode
            state: "off"
          - condition: template
            value_template: >
              {% set temp = state_attr(!input weersensor, 'temperature') %}
              {{ temp is number and temp > !input min_temp and temp < !input max_temp }}
          - condition: template
            value_template: >
              {% set vocht = state_attr(!input weersensor, 'humidity') %}
              {{ vocht is number and vocht > !input min_humidity }}
          - condition: template
            value_template: >
              {% set regen = state_attr(!input weersensor, 'precipitation') | float(0) %}
              {{ regen < !input max_rain }}

      - condition: template
        value_template: "{{ trigger.platform == 'device' }}"

action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ trigger.platform == 'device' }}"
        sequence:
          - service: light.turn_on
            target: !input insectenlampen
          - delay:
              minutes: !input override_duration
          - service: light.turn_off
            target: !input insectenlampen

      - conditions:
          - condition: template
            value_template: "{{ states(!input seizoensmodus) == 'Zomerstand' }}"
        sequence:
          - service: light.turn_on
            target: !input insectenlampen
          - delay:
              minutes: !input insect_lamp_duration_summer
          - service: light.turn_off
            target: !input insectenlampen
          - repeat:
              count: !input insect_lamp_cycles_summer
              sequence:
                - delay:
                    minutes: !input pause_between_cycles_summer
                - service: light.turn_on
                  target: !input insectenlampen
                - delay:
                    minutes: !input insect_lamp_duration_summer
                - service: light.turn_off
                  target: !input insectenlampen

      - conditions:
          - condition: template
            value_template: "{{ states(!input seizoensmodus) == 'Winterstand' }}"
        sequence:
          - service: light.turn_on
            target: !input insectenlampen
          - delay:
              minutes: !input insect_lamp_duration_winter
          - service: light.turn_off
            target: !input insectenlampen
          - repeat:
              count: !input insect_lamp_cycles_winter
              sequence:
                - delay:
                    minutes: !input pause_between_cycles_winter
                - service: light.turn_on
                  target: !input insectenlampen
                - delay:
                    minutes: !input insect_lamp_duration_winter
                - service: light.turn_off
                  target: !input insectenlampen

      - conditions:
          - condition: template
            value_template: "{{ states(!input seizoensmodus) == 'Herfststand' }}"
        sequence:
          - service: light.turn_on
            target: !input insectenlampen
          - delay:
              minutes: !input insect_lamp_duration_herfst
          - service: light.turn_off
            target: !input insectenlampen
          - repeat:
              count: !input insect_lamp_cycles_herfst
              sequence:
                - delay:
                    minutes: !input pause_between_cycles_herfst
                - service: light.turn_on
                  target: !input insectenlampen
                - delay:
                    minutes: !input insect_lamp_duration_herfst
                - service: light.turn_off
                  target: !input insectenlampen

      - conditions:
          - condition: template
            value_template: "{{ states(!input seizoensmodus) == 'Lentestand' }}"
        sequence:
          - service: light.turn_on
            target: !input insectenlampen
          - delay:
              minutes: !input insect_lamp_duration_lente
          - service: light.turn_off
            target: !input insectenlampen
          - repeat:
              count: !input insect_lamp_cycles_lente
              sequence:
                - delay:
                    minutes: !input pause_between_cycles_lente
                - service: light.turn_on
                  target: !input insectenlampen
                - delay:
                    minutes: !input insect_lamp_duration_lente
                - service: light.turn_off
                  target: !input insectenlampen
    default:
      - service: light.turn_off
        target: !input insectenlampen

mode: restart
