blueprint:
  name: GMS Insecten Verdelging v4.38lights+override
  description: >
    Automatische en handmatige aansturing van insectenlampen met seizoenslogica,
    weersvoorwaarden, en override-knop met instelbare duur.
  domain: automation
  input:
    insectenlampen:
      name: Insectenlampen
      selector:
        target:
          entity:
            domain: light

    weersensor:
      name: Weersensor (weather-entity)
      selector:
        entity:
          domain: weather

    vacation_mode:
      name: Vakantiemodus (input_boolean)
      selector:
        entity:
          domain: input_boolean

    seizoensmodus:
      name: Seizoensmodus (input_select)
      selector:
        entity:
          domain: input_select

    # Override knop
    override_device:
      name: Override knop (apparaat)
      selector:
        device:

    override_button:
      name: Knopnummer op apparaat (zoals '1' of '2')
      selector:
        number:

    override_duration:
      name: Duur handmatige override (minuten)
      default: 60
      selector:
        number:
          min: 1
          max: 180
          unit_of_measurement: minuten
          mode: slider

    # Algemeen weerfilter
    max_rain:
      name: Max neerslag (mm/u)
      default: 0.5
      selector:
        number:
          min: 0
          max: 5
          step: 0.1
          unit_of_measurement: mm/u

    min_temp:
      name: Min. temperatuur (째C)
      default: 13
      selector:
        number:
          min: -10
          max: 40
          unit_of_measurement: 째C

    max_temp:
      name: Max. temperatuur (째C)
      default: 35
      selector:
        number:
          min: -10
          max: 40
          unit_of_measurement: 째C

    min_humidity:
      name: Min. luchtvochtigheid (%)
      default: 60
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: '%'

    # Zomer
    insect_lamp_duration_summer:
      name: Aantijd zomer (min)
      default: 15
      selector:
        number:
          min: 1
          max: 60

    insect_lamp_cycles_summer:
      name: Herhalingen zomer
      default: 4
      selector:
        number:
          min: 0
          max: 10

    insect_lamp_pause_summer:
      name: Pauze zomer (min)
      default: 30
      selector:
        number:
          min: 1
          max: 180

    # Winter
    insect_lamp_duration_winter:
      name: Aantijd winter (min)
      default: 10
      selector:
        number:
          min: 1
          max: 60

    insect_lamp_cycles_winter:
      name: Herhalingen winter
      default: 2
      selector:
        number:
          min: 0
          max: 10

    insect_lamp_pause_winter:
      name: Pauze winter (min)
      default: 60
      selector:
        number:
          min: 1
          max: 180

    # Herfst
    insect_lamp_duration_fall:
      name: Aantijd herfst (min)
      default: 9
      selector:
        number:
          min: 1
          max: 60

    insect_lamp_cycles_fall:
      name: Herhalingen herfst
      default: 2
      selector:
        number:
          min: 0
          max: 10

    insect_lamp_pause_fall:
      name: Pauze herfst (min)
      default: 45
      selector:
        number:
          min: 1
          max: 180

    # Lente
    insect_lamp_duration_spring:
      name: Aantijd lente (min)
      default: 12
      selector:
        number:
          min: 1
          max: 60

    insect_lamp_cycles_spring:
      name: Herhalingen lente
      default: 3
      selector:
        number:
          min: 0
          max: 10

    insect_lamp_pause_spring:
      name: Pauze lente (min)
      default: 45
      selector:
        number:
          min: 1
          max: 180

variables:
  weersensor_var: !input weersensor
  vacation_var: !input vacation_mode
  seizoensmodus_var: "{{ states('!input seizoensmodus') }}"
  override_triggered: "{{ trigger.platform == 'device' }}"
  max_rain_var: !input max_rain
  min_temp_var: !input min_temp
  max_temp_var: !input max_temp
  min_humidity_var: !input min_humidity

trigger:
  - platform: time
    at: "00:00:00"

  - platform: time_pattern
    hours: "/2"
    minutes: 0

  - platform: device
    device_id: !input override_device
    domain: hue
    type: initial_press
    subtype: !input override_button

action:
  - choose:
      # Override - handmatige inschakeling via knop
      - conditions:
          - condition: template
            value_template: "{{ override_triggered }}"
        sequence:
          - service: light.turn_on
            target: !input insectenlampen

          - delay:
              minutes: "{{ iif(is_number(states('input_number.override_duration')), states('input_number.override_duration') | int, 60) }}"

          - service: light.turn_off
            target: !input insectenlampen

      # Automatische seizoenslogica
      - conditions:
          - condition: state
            entity_id: !input vacation_mode
            state: "off"
          - condition: template
            value_template: >-
              {% set t = state_attr(weersensor_var, 'temperature') %}
              {{ t is number and t > min_temp_var and t < max_temp_var }}
          - condition: template
            value_template: >-
              {% set h = state_attr(weersensor_var, 'humidity') %}
              {{ h is number and h > min_humidity_var }}
          - condition: template
            value_template: >-
              {% set r = state_attr(weersensor_var, 'precipitation') | float(0) %}
              {{ r < max_rain_var }}
        sequence:
          - choose:
              - conditions: "{{ seizoensmodus_var == 'Zomerstand' }}"
                sequence:
                  - repeat:
                      count: !input insect_lamp_cycles_summer
                      sequence:
                        - service: light.turn_on
                          target: !input insectenlampen
                        - delay:
                            minutes: !input insect_lamp_duration_summer
                        - service: light.turn_off
                          target: !input insectenlampen
                        - delay:
                            minutes: !input insect_lamp_pause_summer

              - conditions: "{{ seizoensmodus_var == 'Winterstand' }}"
                sequence:
                  - repeat:
                      count: !input insect_lamp_cycles_winter
                      sequence:
                        - service: light.turn_on
                          target: !input insectenlampen
                        - delay:
                            minutes: !input insect_lamp_duration_winter
                        - service: light.turn_off
                          target: !input insectenlampen
                        - delay:
                            minutes: !input insect_lamp_pause_winter

              - conditions: "{{ seizoensmodus_var == 'Herfststand' }}"
                sequence:
                  - repeat:
                      count: !input insect_lamp_cycles_fall
                      sequence:
                        - service: light.turn_on
                          target: !input insectenlampen
                        - delay:
                            minutes: !input insect_lamp_duration_fall
                        - service: light.turn_off
                          target: !input insectenlampen
                        - delay:
                            minutes: !input insect_lamp_pause_fall

              - conditions: "{{ seizoensmodus_var == 'Lentestand' }}"
                sequence:
                  - repeat:
                      count: !input insect_lamp_cycles_spring
                      sequence:
                        - service: light.turn_on
                          target: !input insectenlampen
                        - delay:
                            minutes: !input insect_lamp_duration_spring
                        - service: light.turn_off
                          target: !input insectenlampen
                        - delay:
                            minutes: !input insect_lamp_pause_spring

mode: restart
