blueprint:
  name: GMS Insecten Verdelging v4.33lights+override
  description: >
    Automatische bediening van insectenlampen op basis van seizoensmodi en weersomstandigheden.
    Regen wordt betrouwbaar geïnterpreteerd, ook als de waarde ontbreekt (None = 0).
    Nieuw: handmatige override met afstandsbediening.
  domain: automation
  input:
    insectenlampen:
      name: Insectenlampen
      description: Selecteer de insectenlampen (alleen lights).
      selector:
        target:
          entity:
            domain: light

    weersensor:
      name: Weersensor
      selector:
        entity:
          domain: weather

    vacation_mode:
      name: Vakantiemodus
      selector:
        entity:
          domain: input_boolean

    seizoensmodus:
      name: Seizoensmodus
      selector:
        entity:
          domain: input_select

    min_temp:
      name: Minimale Temperatuur
      default: 13
      selector:
        number:
          min: 0
          max: 25
          unit_of_measurement: '°C'

    max_temp:
      name: Maximale Temperatuur
      default: 35
      selector:
        number:
          min: 25
          max: 40
          unit_of_measurement: '°C'

    min_humidity:
      name: Minimale Luchtvochtigheid
      default: 60
      selector:
        number:
          min: 50
          max: 70
          unit_of_measurement: "%"

    max_rain:
      name: Maximale Regenintensiteit
      default: 0.5
      selector:
        number:
          min: 0
          max: 2
          unit_of_measurement: "mm/h"

    insect_lamp_duration_summer:
      name: Zomer - Tijd aan (minuten)
      default: 15
      selector:
        number:
          min: 5
          max: 60
          unit_of_measurement: "minuten"

    insect_lamp_cycles_summer:
      name: Zomer - Aantal cycli
      default: 4
      selector:
        number:
          min: 1
          max: 10
          unit_of_measurement: "cycli"

    pause_between_cycles_summer:
      name: Zomer - Pauze (minuten)
      default: 30
      selector:
        number:
          min: 10
          max: 60
          unit_of_measurement: "minuten"

    insect_lamp_duration_winter:
      name: Winter - Tijd aan (minuten)
      default: 10
      selector:
        number:
          min: 5
          max: 60
          unit_of_measurement: "minuten"

    insect_lamp_cycles_winter:
      name: Winter - Aantal cycli
      default: 2
      selector:
        number:
          min: 1
          max: 5
          unit_of_measurement: "cycli"

    pause_between_cycles_winter:
      name: Winter - Pauze (minuten)
      default: 60
      selector:
        number:
          min: 30
          max: 120
          unit_of_measurement: "minuten"

    insect_lamp_duration_herfst:
      name: Herfst - Tijd aan (minuten)
      default: 9
      selector:
        number:
          min: 5
          max: 60
          unit_of_measurement: "minuten"

    insect_lamp_cycles_herfst:
      name: Herfst - Aantal cycli
      default: 2
      selector:
        number:
          min: 1
          max: 10
          unit_of_measurement: "cycli"

    pause_between_cycles_herfst:
      name: Herfst - Pauze (minuten)
      default: 45
      selector:
        number:
          min: 10
          max: 90
          unit_of_measurement: "minuten"

    insect_lamp_duration_lente:
      name: Lente - Tijd aan (minuten)
      default: 12
      selector:
        number:
          min: 5
          max: 60
          unit_of_measurement: "minuten"

    insect_lamp_cycles_lente:
      name: Lente - Aantal cycli
      default: 3
      selector:
        number:
          min: 1
          max: 10
          unit_of_measurement: "cycli"

    pause_between_cycles_lente:
      name: Lente - Pauze (minuten)
      default: 45
      selector:
        number:
          min: 10
          max: 90
          unit_of_measurement: "minuten"

    override_device:
      name: Afstandsbediening (optioneel)
      default: ''
      selector:
        device:
          filter:
            - integration: hue

    override_button:
      name: Knopnummer (1-4)
      default: '1'
      selector:
        select:
          options:
            - '1'
            - '2'
            - '3'
            - '4'

    override_duration:
      name: Override duur (minuten)
      default: 60
      selector:
        number:
          min: 10
          max: 180
          unit_of_measurement: "minuten"

trigger:
  - platform: time
    at: "00:00:00"
  - platform: time_pattern
    hours: "/2"
    minutes: 0
  - platform: device
    device_id: !input override_device
    domain: hue
    type: initial_press
    subtype: !input override_button

variables:
  weersensor_var: !input weersensor
  max_rain_var: !input max_rain
  min_temp_var: !input min_temp
  max_temp_var: !input max_temp
  min_humidity_var: !input min_humidity
  vacation_var: !input vacation_mode
  seizoensmodus_var: "{{ states(!input seizoensmodus) }}"
  override_duration_var: !input override_duration

condition: []

action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ trigger.platform == 'device' }}"
        sequence:
          - service: light.turn_on
            target: !input insectenlampen
          - delay:
              minutes: "{{ override_duration_var }}"
          - service: light.turn_off
            target: !input insectenlampen

      - conditions:
          - condition: state
            entity_id: !input vacation_mode
            state: "off"
          - condition: template
            value_template: >
              {% set temp = state_attr(weersensor_var, 'temperature') %}
              {{ temp is number and temp > min_temp_var and temp < max_temp_var }}
          - condition: template
            value_template: >
              {% set vocht = state_attr(weersensor_var, 'humidity') %}
              {{ vocht is number and vocht > min_humidity_var }}
          - condition: template
            value_template: >
              {% set regen = state_attr(weersensor_var, 'precipitation') | float(0) %}
              {{ regen < max_rain_var }}
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ seizoensmodus_var == 'Zomerstand' }}"
                sequence:
                  - service: light.turn_on
                    target: !input insectenlampen
                  - delay:
                      minutes: !input insect_lamp_duration_summer
                  - service: light.turn_off
                    target: !input insectenlampen
                  - repeat:
                      count: !input insect_lamp_cycles_summer
                      sequence:
                        - delay:
                            minutes: !input pause_between_cycles_summer
                        - service: light.turn_on
                          target: !input insectenlampen
                        - delay:
                            minutes: !input insect_lamp_duration_summer
                        - service: light.turn_off
                          target: !input insectenlampen

              - conditions:
                  - condition: template
                    value_template: "{{ seizoensmodus_var == 'Winterstand' }}"
                sequence:
                  - service: light.turn_on
                    target: !input insectenlampen
                  - delay:
                      minutes: !input insect_lamp_duration_winter
                  - service: light.turn_off
                    target: !input insectenlampen
                  - repeat:
                      count: !input insect_lamp_cycles_winter
                      sequence:
                        - delay:
                            minutes: !input pause_between_cycles_winter
                        - service: light.turn_on
                          target: !input insectenlampen
                        - delay:
                            minutes: !input insect_lamp_duration_winter
                        - service: light.turn_off
                          target: !input insectenlampen

              - conditions:
                  - condition: template
                    value_template: "{{ seizoensmodus_var == 'Herfststand' }}"
                sequence:
                  - service: light.turn_on
                    target: !input insectenlampen
                  - delay:
                      minutes: !input insect_lamp_duration_herfst
                  - service: light.turn_off
                    target: !input insectenlampen
                  - repeat:
                      count: !input insect_lamp_cycles_herfst
                      sequence:
                        - delay:
                            minutes: !input pause_between_cycles_herfst
                        - service: light.turn_on
                          target: !input insectenlampen
                        - delay:
                            minutes: !input insect_lamp_duration_herfst
                        - service: light.turn_off
                          target: !input insectenlampen

              - conditions:
                  - condition: template
                    value_template: "{{ seizoensmodus_var == 'Lentestand' }}"
                sequence:
                  - service: light.turn_on
                    target: !input insectenlampen
                  - delay:
                      minutes: !input insect_lamp_duration_lente
                  - service: light.turn_off
                    target: !input insectenlampen
                  - repeat:
                      count: !input insect_lamp_cycles_lente
                      sequence:
                        - delay:
                            minutes: !input pause_between_cycles_lente
                        - service: light.turn_on
                          target: !input insectenlampen
                        - delay:
                            minutes: !input insect_lamp_duration_lente
                        - service: light.turn_off
                          target: !input insectenlampen
    default:
      - service: light.turn_off
        target: !input insectenlampen

mode: restart
