blueprint:
  name: GMS Insecten Verdelging v4.47lights
  description: >
    Automatische bediening van insectenlampen op basis van seizoensmodi en weersomstandigheden.
    Inclusief handmatige override via een geselecteerde Hue-knop.
    Regen wordt betrouwbaar geïnterpreteerd, ook als de waarde ontbreekt of onbekend is (None = 0).
    Deze versie gebruikt 'variables' en veilige templates voor weerdata.

  domain: automation
  input:
    insectenlampen:
      name: Insectenlampen
      description: Selecteer de insectenlampen die je wilt aansturen (alleen lights).
      selector:
        target:
          entity:
            domain: light

    weersensor:
      name: Weersensor
      description: Selecteer de weersensor die temperatuur, luchtvochtigheid en regen meet.
      selector:
        entity:
          domain: weather

    min_temp:
      name: Minimale Temperatuur
      default: 13
      selector:
        number:
          min: 0
          max: 25
          unit_of_measurement: '°C'

    max_temp:
      name: Maximale Temperatuur
      default: 35
      selector:
        number:
          min: 25
          max: 40
          unit_of_measurement: '°C'

    min_humidity:
      name: Minimale Luchtvochtigheid
      default: 60
      selector:
        number:
          min: 50
          max: 70
          unit_of_measurement: "%"

    max_rain:
      name: Maximale Regenintensiteit
      default: 0.5
      selector:
        number:
          min: 0
          max: 2
          unit_of_measurement: "mm/h"

    vacation_mode:
      name: Vakantieschakelaar
      selector:
        entity:
          domain: input_boolean

    seizoensmodus:
      name: Seizoensmodus
      selector:
        entity:
          domain: input_select

    insect_lamp_duration_summer:
      name: Zomer - Tijd aan (minuten)
      default: 15
      selector:
        number:
          min: 5
          max: 60
          unit_of_measurement: "minuten"

    insect_lamp_cycles_summer:
      name: Zomer - Aantal cycli
      default: 4
      selector:
        number:
          min: 1
          max: 10
          unit_of_measurement: "cycli"

    pause_between_cycles_summer:
      name: Zomer - Pauze (minuten)
      default: 30
      selector:
        number:
          min: 10
          max: 60
          unit_of_measurement: "minuten"

    insect_lamp_duration_winter:
      name: Winter - Tijd aan (minuten)
      default: 10
      selector:
        number:
          min: 5
          max: 60
          unit_of_measurement: "minuten"

    insect_lamp_cycles_winter:
      name: Winter - Aantal cycli
      default: 2
      selector:
        number:
          min: 1
          max: 5
          unit_of_measurement: "cycli"

    pause_between_cycles_winter:
      name: Winter - Pauze (minuten)
      default: 60
      selector:
        number:
          min: 30
          max: 120
          unit_of_measurement: "minuten"

    insect_lamp_duration_herfst:
      name: Herfst - Tijd aan (minuten)
      default: 9
      selector:
        number:
          min: 5
          max: 60
          unit_of_measurement: "minuten"

    insect_lamp_cycles_herfst:
      name: Herfst - Aantal cycli
      default: 2
      selector:
        number:
          min: 1
          max: 10
          unit_of_measurement: "cycli"

    pause_between_cycles_herfst:
      name: Herfst - Pauze (minuten)
      default: 45
      selector:
        number:
          min: 10
          max: 90
          unit_of_measurement: "minuten"

    insect_lamp_duration_lente:
      name: Lente - Tijd aan (minuten)
      default: 12
      selector:
        number:
          min: 5
          max: 60
          unit_of_measurement: "minuten"

    insect_lamp_cycles_lente:
      name: Lente - Aantal cycli
      default: 3
      selector:
        number:
          min: 1
          max: 10
          unit_of_measurement: "cycli"

    pause_between_cycles_lente:
      name: Lente - Pauze (minuten)
      default: 45
      selector:
        number:
          min: 10
          max: 90
          unit_of_measurement: "minuten"

    override_device:
      name: Override-knop
      selector:
        device:

    override_event_code:
      name: Gebeurteniscode knop (bijv. "1002")
      default: "1002"
      selector:
        number:
          min: 1
          max: 4
          mode: box
                 
    override_duration:
      name: Duur handmatige override (minuten)
      default: 60
      selector:
        number:
          min: 5
          max: 180
          unit_of_measurement: "minuten"

triggers:
  - platform: time
    at: "00:00:00"
  - platform: time_pattern
    hours: "/2"
    minutes: 0
  - platform: event
    event_type: hue_event
    event_data:
      device_id: !input override_device
      type: short_release
      subtype: !input override_event_code

variables:
  weersensor_var: !input weersensor
  max_rain_var: !input max_rain
  min_temp_var: !input min_temp
  max_temp_var: !input max_temp
  min_humidity_var: !input min_humidity
  vacation_var: !input vacation_mode
  override_minutes: !input override_duration

condition:
  - condition: template
    value_template: >
      {{ trigger.platform != 'device' and is_state(vacation_var, 'off') }}

  - condition: template
    value_template: >
      {% set temp = state_attr(weersensor_var, 'temperature') %}
      {{ temp is number and temp > min_temp_var and temp < max_temp_var }}

  - condition: template
    value_template: >
      {% set vocht = state_attr(weersensor_var, 'humidity') %}
      {{ vocht is number and vocht > min_humidity_var }}

  - condition: template
    value_template: >
      {% set regen = state_attr(weersensor_var, 'precipitation') | float(0) %}
      {{ regen < max_rain_var }}

action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ trigger.platform == 'device' }}"
        sequence:
          - service: light.turn_on
            target: !input insectenlampen
          - delay:
              minutes: "{{ override_minutes }}"
          - service: light.turn_off
            target: !input insectenlampen

      - conditions:
          - condition: template
            value_template: "{{ states('input_select.seizoensmodus') == 'Zomerstand' }}"
        sequence:
          - service: light.turn_on
            target: !input insectenlampen
          - delay:
              minutes: !input insect_lamp_duration_summer
          - service: light.turn_off
            target: !input insectenlampen
          - repeat:
              count: !input insect_lamp_cycles_summer
              sequence:
                - delay:
                    minutes: !input pause_between_cycles_summer
                - service: light.turn_on
                  target: !input insectenlampen
                - delay:
                    minutes: !input insect_lamp_duration_summer
                - service: light.turn_off
                  target: !input insectenlampen

      - conditions:
          - condition: template
            value_template: "{{ states('input_select.seizoensmodus') == 'Winterstand' }}"
        sequence:
          - service: light.turn_on
            target: !input insectenlampen
          - delay:
              minutes: !input insect_lamp_duration_winter
          - service: light.turn_off
            target: !input insectenlampen
          - repeat:
              count: !input insect_lamp_cycles_winter
              sequence:
                - delay:
                    minutes: !input pause_between_cycles_winter
                - service: light.turn_on
                  target: !input insectenlampen
                - delay:
                    minutes: !input insect_lamp_duration_winter
                - service: light.turn_off
                  target: !input insectenlampen

      - conditions:
          - condition: template
            value_template: "{{ states('input_select.seizoensmodus') == 'Herfststand' }}"
        sequence:
          - service: light.turn_on
            target: !input insectenlampen
          - delay:
              minutes: !input insect_lamp_duration_herfst
          - service: light.turn_off
            target: !input insectenlampen
          - repeat:
              count: !input insect_lamp_cycles_herfst
              sequence:
                - delay:
                    minutes: !input pause_between_cycles_herfst
                - service: light.turn_on
                  target: !input insectenlampen
                - delay:
                    minutes: !input insect_lamp_duration_herfst
                - service: light.turn_off
                  target: !input insectenlampen

      - conditions:
          - condition: template
            value_template: "{{ states('input_select.seizoensmodus') == 'Lentestand' }}"
        sequence:
          - service: light.turn_on
            target: !input insectenlampen
          - delay:
              minutes: !input insect_lamp_duration_lente
          - service: light.turn_off
            target: !input insectenlampen
          - repeat:
              count: !input insect_lamp_cycles_lente
              sequence:
                - delay:
                    minutes: !input pause_between_cycles_lente
                - service: light.turn_on
                  target: !input insectenlampen
                - delay:
                    minutes: !input insect_lamp_duration_lente
                - service: light.turn_off
                  target: !input insectenlampen
    default:
      - service: light.turn_off
        target: !input insectenlampen

mode: restart
