blueprint:
  name: GMS Insecten Verdelging v4.40lights+override
  description: >
    Automatische bediening van insectenlampen op basis van seizoensmodi en weersomstandigheden.
    Inclusief handmatige override via Hue-knop.
  domain: automation
  input:
    insectenlampen:
      name: Insectenlampen
      selector:
        target:
          entity:
            domain: light

    weersensor:
      name: Weersensor
      selector:
        entity:
          domain: weather

    vacation_mode:
      name: Vakantieschakelaar
      selector:
        entity:
          domain: input_boolean

    seizoensmodus:
      name: Seizoensmodus
      selector:
        entity:
          domain: input_select

    min_temp:
      name: Minimale Temperatuur
      default: 13
      selector:
        number:
          min: 0
          max: 25
          unit_of_measurement: "°C"

    max_temp:
      name: Maximale Temperatuur
      default: 35
      selector:
        number:
          min: 25
          max: 40
          unit_of_measurement: "°C"

    min_humidity:
      name: Minimale Luchtvochtigheid
      default: 60
      selector:
        number:
          min: 50
          max: 70
          unit_of_measurement: "%"

    max_rain:
      name: Maximale Regenintensiteit
      default: 0.5
      selector:
        number:
          min: 0
          max: 2
          unit_of_measurement: "mm/h"

    insect_lamp_duration_summer:
      name: Zomer - Tijd aan (minuten)
      default: 15
      selector:
        number:
          min: 5
          max: 60
          unit_of_measurement: "minuten"

    insect_lamp_cycles_summer:
      name: Zomer - Aantal cycli
      default: 4
      selector:
        number:
          min: 1
          max: 10
          unit_of_measurement: "cycli"

    pause_between_cycles_summer:
      name: Zomer - Pauze (minuten)
      default: 30
      selector:
        number:
          min: 10
          max: 60
          unit_of_measurement: "minuten"

    insect_lamp_duration_winter:
      name: Winter - Tijd aan (minuten)
      default: 10
      selector:
        number:
          min: 5
          max: 60
          unit_of_measurement: "minuten"

    insect_lamp_cycles_winter:
      name: Winter - Aantal cycli
      default: 2
      selector:
        number:
          min: 1
          max: 5
          unit_of_measurement: "cycli"

    pause_between_cycles_winter:
      name: Winter - Pauze (minuten)
      default: 60
      selector:
        number:
          min: 30
          max: 120
          unit_of_measurement: "minuten"

    insect_lamp_duration_herfst:
      name: Herfst - Tijd aan (minuten)
      default: 9
      selector:
        number:
          min: 5
          max: 60
          unit_of_measurement: "minuten"

    insect_lamp_cycles_herfst:
      name: Herfst - Aantal cycli
      default: 2
      selector:
        number:
          min: 1
          max: 10
          unit_of_measurement: "cycli"

    pause_between_cycles_herfst:
      name: Herfst - Pauze (minuten)
      default: 45
      selector:
        number:
          min: 10
          max: 90
          unit_of_measurement: "minuten"

    insect_lamp_duration_lente:
      name: Lente - Tijd aan (minuten)
      default: 12
      selector:
        number:
          min: 5
          max: 60
          unit_of_measurement: "minuten"

    insect_lamp_cycles_lente:
      name: Lente - Aantal cycli
      default: 3
      selector:
        number:
          min: 1
          max: 10
          unit_of_measurement: "cycli"

    pause_between_cycles_lente:
      name: Lente - Pauze (minuten)
      default: 45
      selector:
        number:
          min: 10
          max: 90
          unit_of_measurement: "minuten"

    override_device:
      name: Override-knop (Hue afstandsbediening)
      selector:
        device:
          integration: hue

    override_button:
      name: Knopnummer voor override
      default: "1"
      selector:
        select:
          options:
            - "1"
            - "2"
            - "3"
            - "4"

    override_duration:
      name: Duur override (minuten)
      default: 60
      selector:
        number:
          min: 5
          max: 180
          unit_of_measurement: "minuten"

mode: restart

variables:
  seizoensmodus_var: "{{ states(inputs.seizoensmodus) }}"
  weersensor_var: "{{ inputs.weersensor }}"
  vacation_var: "{{ inputs.vacation_mode }}"
  override_triggered: "{{ trigger.platform == 'device' }}"
  max_rain_var: "{{ inputs.max_rain }}"
  min_temp_var: "{{ inputs.min_temp }}"
  max_temp_var: "{{ inputs.max_temp }}"
  min_humidity_var: "{{ inputs.min_humidity }}"
  duration_map:
    Zomerstand: [{{ inputs.insect_lamp_duration_summer }}, {{ inputs.insect_lamp_cycles_summer }}, {{ inputs.pause_between_cycles_summer }}]
    Winterstand: [{{ inputs.insect_lamp_duration_winter }}, {{ inputs.insect_lamp_cycles_winter }}, {{ inputs.pause_between_cycles_winter }}]
    Herfststand: [{{ inputs.insect_lamp_duration_herfst }}, {{ inputs.insect_lamp_cycles_herfst }}, {{ inputs.pause_between_cycles_herfst }}]
    Lentestand: [{{ inputs.insect_lamp_duration_lente }}, {{ inputs.insect_lamp_cycles_lente }}, {{ inputs.pause_between_cycles_lente }}]

trigger:
  - platform: time
    at: "00:00:00"
  - platform: time_pattern
    hours: "/2"
    minutes: 0
  - platform: device
    device_id: !input override_device
    domain: hue
    type: initial_press
    subtype: !input override_button

condition: []

action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ override_triggered }}"
        sequence:
          - service: light.turn_on
            target: !input insectenlampen
          - delay:
              minutes: !input override_duration
          - service: light.turn_off
            target: !input insectenlampen

      - conditions:
          - condition: state
            entity_id: !input vacation_mode
            state: "off"
          - condition: template
            value_template: >
              {% set t = state_attr(weersensor_var, 'temperature') %}
              {{ t is number and t > min_temp_var and t < max_temp_var }}
          - condition: template
            value_template: >
              {% set h = state_attr(weersensor_var, 'humidity') %}
              {{ h is number and h > min_humidity_var }}
          - condition: template
            value_template: >
              {% set r = state_attr(weersensor_var, 'precipitation') | float(0) %}
              {{ r < max_rain_var }}
        sequence:
          - variables:
              duur: "{{ duration_map[seizoensmodus_var][0] }}"
              cycli: "{{ duration_map[seizoensmodus_var][1] }}"
              pauze: "{{ duration_map[seizoensmodus_var][2] }}"
          - repeat:
              count: "{{ cycli }}"
              sequence:
                - service: light.turn_on
                  target: !input insectenlampen
                - delay:
                    minutes: "{{ duur }}"
                - service: light.turn_off
                  target: !input insectenlampen
                - delay:
                    minutes: "{{ pauze }}"
