blueprint:
  name: Insectenlamp Automatisering v4.01
  description: >
    Automatische bediening van insectenlampen op basis van weersomstandigheden en seizoensmodi.
    De automatisering synchroniseert elke 2 uur na middernacht en controleert de weersomstandigheden
    (temperatuur, luchtvochtigheid, regen) om te bepalen of het nodig is om de lampen in te schakelen.
    In deze versie is nieuwe logica toegepast, instelbare delay en een default off.

  domain: automation
  input:
    insectenlampen:
      name: Insectenlampen
      description: Selecteer de insectenlampen die je wilt aansturen (zowel switches als lights).
      selector:
        target:
          entity:
            domain:
              - switch
              - light

    weersensor:
      name: Weersensor
      description: Selecteer de weersensor die temperatuur, luchtvochtigheid en regen meet.
      selector:
        entity:
          domain: weather

    min_temp:
      name: Minimale Temperatuur
      description: Muggen zijn vooral actief bij temperaturen boven 10째C. Stel hier de minimale buitentemperatuur in voor de activering van de insectenlampen.
      default: 12
      selector:
        number:
          min: 0
          max: 25
          unit_of_measurement: '째C'

    max_temp:
      name: Maximale Temperatuur
      description: Muggen zijn minder actief bij temperaturen boven 35째C. Stel hier de maximale buitentemperatuur in voor de activering van de insectenlampen.
      default: 35
      selector:
        number:
          min: 25
          max: 40
          unit_of_measurement: '째C'

    min_humidity:
      name: Minimale Luchtvochtigheid
      description: Muggen zijn het meest actief bij een luchtvochtigheid van meer dan 60%. Stel de minimum luchtvochtigheid in voor de activering van de insectenlampen.
      default: 60
      selector:
        number:
          min: 50
          max: 70
          unit_of_measurement: "%"

    max_rain:
      name: Maximale Regenintensiteit
      description: >
        Boven de 2 mm/uur (hevige regen) neemt de kans toe dat muggenlarven worden weggespoeld en je dus minder last hebt van muggen. 
        Stel een maximum in tot 2 mm/uur. Advieswaarde: 0,5 mm/uur.
      default: 0.5
      selector:
        number:
          min: 0
          max: 2
          unit_of_measurement: "mm/h"

    vacation_mode:
      name: Vakantieschakelaar
      description: >
        Schakel de vakantiemodus in. Als deze modus is ingeschakeld, blijven de insectenlampen uit.
      selector:
        entity:
          domain: input_boolean

    seizoensmodus:
      name: Seizoensmodus
      description: Selecteer de seizoensmodus (Zomerstand, Winterstand, Herfststand, Lentestand).
      selector:
        entity:
          domain: input_select

    insect_lamp_duration_herfst:
      name: Herfst - Tijd dat de lamp aan blijft (in minuten)
      description: >
        Stel de duur in dat de insectenlamp aanblijft in de herfst.
      default: 12
      selector:
        number:
          min: 5
          max: 60
          unit_of_measurement: "minuten"

    insect_lamp_cycles_herfst:
      name: Herfst - Aantal activatiecycli per avond
      description: >
        Stel in hoe vaak de insectenlamp per avond wordt geactiveerd in de herfst.
      default: 3
      selector:
        number:
          min: 1
          max: 10
          unit_of_measurement: "cycli"

    pause_between_cycles_herfst:
      name: Herfst - Pauze tussen cycli (in minuten)
      description: >
        Stel de pauzetijd in tussen de activatiecycli.
      default: 45
      selector:
        number:
          min: 5
          max: 120
          unit_of_measurement: "minuten"

trigger:
  - platform: time
    at: "00:00:00"
  - platform: time_pattern
    hours: "/2"
    minutes: 0

condition:
  - condition: numeric_state
    entity_id: !input 'weersensor'
    attribute: temperature
    above: !input 'min_temp'
    below: !input 'max_temp'
  
  - condition: numeric_state
    entity_id: !input 'weersensor'
    attribute: humidity
    above: !input 'min_humidity'

  - condition: numeric_state
    entity_id: !input 'weersensor'
    attribute: precipitation
    below: !input 'max_rain'

action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ states('input_select.seizoensmodus') == 'Herfststand' }}"
        sequence:
          - service: switch.turn_on
            target: !input 'insectenlampen'
          - delay:
              minutes: !input 'insect_lamp_duration_herfst'
          - service: switch.turn_off
            target: !input 'insectenlampen'
          - repeat:
              count: !input 'insect_lamp_cycles_herfst'
              sequence:
                - delay:
                    minutes: !input 'pause_between_cycles_herfst'
                - service: switch.turn_on
                  target: !input 'insectenlampen'
                - delay:
                    minutes: !input 'insect_lamp_duration_herfst'
                - service: switch.turn_off
                  target: !input 'insectenlampen'
      default:
        # Lampen uitzetten als de condities niet voldoen
        - service: switch.turn_off
          target: !input 'insectenlampen'

mode: single
